name = "raindrop-wordpress-sync"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SYNC_STATE"
id = "9ece47fdd41548f7ad9e20b1c493adda"
preview_id = "b5960ba20661492b920ce691d32478d9"

[vars]
TRIGGER_TOKEN = "development-token"
RAINDROP_TAG = "blog"
# Add your Raindrop test token here:
# RAINDROP_TOKEN = "your-test-token-here"