name = "raindrop-wordpress-sync"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SYNC_STATE"
id = "9ece47fdd41548f7ad9e20b1c493adda"
preview_id = "b5960ba20661492b920ce691d32478d9"

[vars]
RAINDROP_TAG = "blog"

[triggers]
crons = ["10 * * * *"]  # Run every hour at minute 10 for automatic sync

# Production secrets (configured via wrangler secret put):
# - RAINDROP_TOKEN ✓
# - WP_USERNAME ✓  
# - WP_APP_PASSWORD ✓
# - WP_ENDPOINT ✓
# - TRIGGER_TOKEN ✓ (overrides vars.TRIGGER_TOKEN in production)